[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$target = 'x86_64-pc-windows-msvc'
$outputPath = Join-Path $repoRoot 'THIRD-PARTY-NOTICES.txt'
$manifests = @(
    @{ Name = 'echowisp'; Path = (Join-Path $repoRoot 'Cargo.toml') },
    @{ Name = 'echowisp-bridge'; Path = (Join-Path $repoRoot 'bridge\Cargo.toml') }
)

function Get-TreePackages {
    param([string]$ManifestPath)

    # Cargo emits a harmless stderr warning in this sandbox when USERPROFILE is
    # virtualised.  Keep native stderr from becoming a terminating PowerShell error.
    $savedErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $lines = & cargo tree --manifest-path $ManifestPath -e normal --target $target --prefix none 2>$null
    $exitCode = $LASTEXITCODE
    $ErrorActionPreference = $savedErrorActionPreference
    if ($exitCode -ne 0) {
        throw "cargo tree failed for $ManifestPath"
    }

    $packages = foreach ($line in $lines) {
        if ($line -match '^([A-Za-z0-9][A-Za-z0-9_-]*) v([0-9][^ ]*)$') {
            [PSCustomObject]@{ Name = $Matches[1]; Version = $Matches[2] }
        }
    }
    return @($packages | Sort-Object Name, Version -Unique)
}

$cargoHome = if ($env:CARGO_HOME) { $env:CARGO_HOME } else { Join-Path $env:USERPROFILE '.cargo' }
$registrySources = Join-Path $cargoHome 'registry\src'
if (-not (Test-Path -LiteralPath $registrySources)) {
    throw "No se encontró el registro local de Cargo: $registrySources"
}

$includedBy = @{}
$byManifest = @{}
foreach ($manifest in $manifests) {
    $packages = Get-TreePackages $manifest.Path
    $byManifest[$manifest.Name] = $packages
    foreach ($package in $packages) {
        $key = "$($package.Name)|$($package.Version)"
        if (-not $includedBy.ContainsKey($key)) { $includedBy[$key] = [System.Collections.Generic.List[string]]::new() }
        $includedBy[$key].Add($manifest.Name)
    }
}

function Get-CrateNotice {
    param([string]$Name, [string]$Version)

    $crateDirectory = Get-ChildItem -LiteralPath $registrySources -Directory | ForEach-Object {
        Get-ChildItem -LiteralPath $_.FullName -Directory -Filter "$Name-$Version" -ErrorAction SilentlyContinue
    } | Sort-Object FullName | Select-Object -First 1
    if ($null -eq $crateDirectory) {
        throw "No se encontró $Name v$Version en el registro local de Cargo."
    }

    $crateManifest = Get-Content -Raw -LiteralPath (Join-Path $crateDirectory.FullName 'Cargo.toml')
    $licenseMatch = [regex]::Match($crateManifest, '(?m)^license\s*=\s*"([^"]+)"')
    $license = if ($licenseMatch.Success) { $licenseMatch.Groups[1].Value } else { 'NO DECLARADA' }
    $licenseFiles = @(Get-ChildItem -LiteralPath $crateDirectory.FullName -File |
        Where-Object { $_.Name -match '^(LICENSE|COPYING)' } |
        Sort-Object Name)
    if ($licenseFiles.Count -eq 0) {
        return [PSCustomObject]@{ License = $license; Text = '[El crate no contiene un archivo LICENSE* ni COPYING* en el registro local.]' }
    }

    return [PSCustomObject]@{ License = $license; Text = (($licenseFiles | ForEach-Object {
        "----- $($_.Name) -----`n" + [System.IO.File]::ReadAllText($_.FullName).TrimEnd()
    }) -join "`n`n") }
}

$content = [System.Collections.Generic.List[string]]::new()
$content.Add('THIRD-PARTY-NOTICES')
$content.Add('===================')
$content.Add('')
$content.Add("Generated by scripts/notices.ps1 from normal Cargo dependencies for $target.")
$content.Add('Do not edit by hand; regenerate before publishing.')
$content.Add('')
$content.Add('Included dependency trees')
$content.Add('--------------------------')
foreach ($manifest in $manifests) {
    $content.Add($manifest.Name + ':')
    foreach ($package in $byManifest[$manifest.Name]) { $content.Add("  $($package.Name) v$($package.Version)") }
    $content.Add('')
}

foreach ($key in ($includedBy.Keys | Sort-Object)) {
    $parts = $key -split '\|', 2
    $name = $parts[0]
    $version = $parts[1]
    $content.Add($name + ' v' + $version)
    $content.Add(('=' * ($name.Length + $version.Length + 2)))
    $notice = Get-CrateNotice $name $version
    $content.Add('License: ' + $notice.License)
    $content.Add('Included by: ' + (($includedBy[$key] | Sort-Object -Unique) -join ', '))
    $content.Add('')
    $content.Add($notice.Text)
    $content.Add('')
}

[System.IO.File]::WriteAllText($outputPath, (($content -join "`n").TrimEnd() + "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath"
